- name: Update APT Package repository cache
  apt:
    update_cache: True
- name: Install MySQL server on   ubuntu 
  apt:
    name: mysql-server
    state: present
- name: Install MySQL client on  ubuntu
  apt:
    name: mysql-server
    state: present
- name: Make sure mysqld service is running
  service:
    name: mysql
    state: started
    enabled: True

- name: Install python3-PyMySQL library
  apt:
    name: python3-pymysql
    state: present
# - name: Set MySQL root Password
#   mysql_user:
#     login_host: 'localhost'
#     login_user: 'root'
#     login_password: ''
#     name: 'root'
#     password: "{{mysql_pass}}"
#     state: present